name: 'Continuous Delivery'

env:
  SERVICE_NAME: api-service
  PROJECT_ID: test-mle
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/test-mle/test-repo/api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --vpc-connector my-connector \
            --region us-east1 \
            --allow-unauthenticated \
            --set-env-vars dataset_id=${{ secrets.dataset_id }},MODELS_BUCKET_NAME=${{ secrets.MODELS_BUCKET_NAME }} \
            --set-env-vars project_id=${{ secrets.project_id }},table_id=${{ secrets.table_id }} \
            --set-env-vars REDIS_HOST=${{ secrets.REDIS_HOST }}